name: Build

on:
  pull_request:
  push:
    tags:
    - '*'
    branches:
    - main

# disable concurrent runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, macos-13]

    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Boost
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew upgrade
        brew install boost
    - name: Install Boost
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -y update
        sudo apt-get -y install libboost-dev libboost-test-dev libboost-program-options-dev libboost-serialization-dev

    - name: ubuntu packages
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y xorg-dev libglu1-mesa-dev xpra xserver-xorg-video-dummy freeglut3-dev

    - name: configure (with AMGCL)
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DSHM_NO_AMGCL=Off

    - name: build demo
      if: runner.os != 'Windows'
      run: cd build && make

    - name: build demo
      if: runner.os == 'Windows'
      run: cd build && cmake --build "." -DSHM_NO_AMGCL=Off
